### ISSUE TITLE
Is this still the development repo?

### ISSUE THREAD

**Issue by eabase** [NordicSemiconductor/pc-nrfconnect-linkmonitor#28]
@datenreisender
Is this still the development repo or is it handled elsewhere?

**Comment by datenreisender** [comment]
Yes, this is the active repo for our LTE Link Monitor app. Why do you ask?

**Comment by eabase** [comment]
> Why do you ask?

I'm asking to make sure I'm in the right place, since none of the reported issues has been commented or addressed. So if you want any PR's I guess that info would be relevant.

**Comment by datenreisender** [comment]
Yes, we could get better at reacting on these. 🙁
